version: '3.4'

services:
  customers:
    image:preetn/ecommerceapicustomers:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"

 orders:
     image:preetn/ecommerceapiorders:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  products:
    image:preetn/ecommerceapiproducts:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  search:
    image:preetn/ecommerceapisearch:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serivces__Products=http://10.0.0.4:19081/lil/products/
      - Serivces__Customers=http://10.0.0.4:19081/lil/customers/
      - Serivces__Orders=http://10.0.0.4:19081/lil/orders/
    ports:
      - "6004:80"

